/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/transaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllAccount"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}/deleteAcount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["deleteAccount"];
        trace?: never;
    };
    "/api/accounts/{accountId}/changeBalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeBalance"];
        trace?: never;
    };
    "/getHistory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountid}/getAccountBalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountFromId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TransactionDTO: {
            /** Format: uuid */
            to_account?: string;
            /** Format: uuid */
            from_account?: string;
            type?: string;
            amount?: number;
            note?: string;
        };
        ApiResponseReturnDataClass: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClass"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ErrorDetail: {
            code?: string;
            details?: string;
        };
        ReturnDataClass: {
            transactionList?: components["schemas"]["TransactionModel"][];
        };
        TransactionModel: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            fromAccountId?: string;
            /** Format: uuid */
            toAccountId?: string;
            amount?: number;
            /** @enum {string} */
            transaction_type?: "WITHDRAW" | "DEPOSIT" | "TRANSFER";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
            reference_no?: string;
            note?: string;
            /** Format: date-time */
            created_at?: string;
        };
        UserModel: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            passwordHash?: string;
            phone?: string;
            /** @enum {string} */
            role?: "CUSTOMER" | "ADMIN";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LoginDTO: {
            email?: string;
            password?: string;
        };
        ApiResponseMapStringString: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: string;
            };
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        CreateAccountRequest: {
            /** @enum {string} */
            accountType: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            initialDeposit?: number;
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBalanceResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BalanceResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        BalanceResponse: {
            accountNumber?: string;
            balance?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClass"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClass"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringString"];
                };
            };
        };
    };
    getAllAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeBalance: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClass"];
                };
            };
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBalanceResponse"];
                };
            };
        };
    };
    getAccountFromId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
}
