/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllUser"];
        put: operations["editUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["approveRequest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/refreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllTransaction"];
        put?: never;
        post: operations["postTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllRequest"];
        put?: never;
        post: operations["postRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllAccount"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/deleteAcount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["deleteAccount"];
        trace?: never;
    };
    "/accounts/{accountId}/changeBalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeBalance"];
        trace?: never;
    };
    "/accounts/{accountId}/changeAccountType": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeAccountType"];
        trace?: never;
    };
    "/accounts/{accountId}/changeAccountStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeAccountStatus"];
        trace?: never;
    };
    "/transactions/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransactionByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/history/{accNum}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountid}/getAccountBalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountFromId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDTO: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            /** @enum {string} */
            role?: "CUSTOMER" | "ADMIN";
            phone?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date */
            birthDay?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
        };
        ApiResponseUserModel: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserModel"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ErrorDetail: {
            code?: string;
            details?: string;
        };
        UserModel: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            passwordHash?: string;
            phone?: string;
            /** @enum {string} */
            role?: "CUSTOMER" | "ADMIN";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date */
            birthDate?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
        };
        ChangePasswordDTO: {
            email?: string;
            oldPassword?: string;
            newPassword?: string;
        };
        UpdateProfileDTO: {
            fullName?: string;
            phone?: string;
        };
        ApiResponseReturnClass: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnClass"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnClass: {
            /** Format: date-time */
            timestamp?: string;
            data?: components["schemas"]["ReturnDataClass"];
            userLogin?: components["schemas"]["UserModel"];
            refreshToken?: string;
            error?: boolean;
            msg?: string;
            code?: string;
            success?: boolean;
            MSG?: string;
            Code?: string;
        };
        ReturnDataClass: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: Record<string, never>[];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        TransactionDTO: {
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            from_account_id?: string;
            /** @enum {string} */
            type?: "WITHDRAW" | "DEPOSIT" | "TRANSFER";
            amount?: number;
            note?: string;
            reference_no?: string;
            to_account_number?: string;
            from_account_number?: string;
            /** Format: date-time */
            created_at?: string;
        };
        UserAccountResponse: {
            /** Format: uuid */
            id?: string;
            accountNumber?: string;
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
        };
        ApiResponseReturnDataClass: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClass"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseMapStringObject: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: Record<string, never>;
            };
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        LoginDTO: {
            email?: string;
            password?: string;
        };
        ApiResponseListTransactionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TransactionDTO"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListStockModel: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StockModel"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        StockModel: {
            symbol?: string;
            name?: string;
            type?: string;
        };
        Account: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RequestDTO: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            requestType?: "OPEN_ACCOUNT" | "CHANGE_ACCOUNT_STATUS" | "CHANGE_ACCOUNT_TYPE";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            data?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            approvedAt?: string;
            account?: components["schemas"]["Account"];
            approveBy?: components["schemas"]["UserModel"];
            accountRequest?: components["schemas"]["AccountResponse"];
        };
        ApiResponseRequestDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["RequestDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        CreateAccountRequest: {
            /** @enum {string} */
            accountType: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            initialDeposit?: number;
        };
        ApiResponseAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ChangeAccountTypeRequest: {
            accountType: string;
        };
        ChangeStatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
        };
        ApiResponseReturnDataClassUserDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassUserDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassUserDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["UserDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseReturnDataClassTransactionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassTransactionDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassTransactionDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["TransactionDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseReturnDataClassRequestDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassRequestDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassRequestDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["RequestDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseListAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBalanceResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BalanceResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        BalanceResponse: {
            accountNumber?: string;
            balance?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseListUserAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserAccountResponse"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllUser: {
        parameters: {
            query: {
                size: number;
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassUserDTO"];
                };
            };
        };
    };
    editUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    approveRequest: {
        parameters: {
            query: {
                isApprove: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnClass"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClass"];
                };
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    getAllTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionDTO"];
                };
            };
        };
    };
    postTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionDTO"];
                };
            };
        };
    };
    importStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListStockModel"];
                };
            };
        };
    };
    getAllRequest: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassRequestDTO"];
                };
            };
        };
    };
    postRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestDTO"];
                };
            };
        };
    };
    getAllAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeBalance: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeAccountType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeAccountTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    getTransactionByUserId: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassTransactionDTO"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path: {
                accNum: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassTransactionDTO"];
                };
            };
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBalanceResponse"];
                };
            };
        };
    };
    getAccountFromId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    getAccountByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUserAccountResponse"];
                };
            };
        };
    };
}
