/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllUser"];
        put: operations["editUser"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["approveRequest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/portfolio/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["approvePortRequest"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["approveOrder"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/refreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllTransaction"];
        put?: never;
        post: operations["postTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllStock"];
        put?: never;
        post: operations["importStock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllRequest"];
        put?: never;
        post: operations["postRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPortfolioRequest"];
        put?: never;
        post: operations["postPortfolioRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllOrder"];
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllAccount"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeAccountType"];
        trace?: never;
    };
    "/accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeAccountStatus"];
        trace?: never;
    };
    "/accounts/{accountId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["changeBalance"];
        trace?: never;
    };
    "/transactions/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTransactionByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/history/{accNum}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/price/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStockPrice"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPortfolioByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllRequest_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllOrderByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountid}/getAccountBalance": {
    "/accounts/{accountid}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountFromId"];
        put?: never;
        post?: never;
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAccountByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllAccountAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserDTO: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            /** @enum {string} */
            role?: "CUSTOMER" | "ADMIN";
            phone?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date */
            birthDay?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
        };
        ApiResponseUserModel: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["UserModel"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ErrorDetail: {
            code?: string;
            details?: string;
        };
        UserModel: {
            /** Format: uuid */
            id?: string;
            fullName?: string;
            email?: string;
            passwordHash?: string;
            phone?: string;
            /** @enum {string} */
            role?: "CUSTOMER" | "ADMIN";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date */
            birthDate?: string;
            /** @enum {string} */
            gender?: "male" | "female" | "other";
        };
        ChangePasswordDTO: {
            email?: string;
            oldPassword?: string;
            newPassword?: string;
        };
        UpdateProfileDTO: {
            fullName?: string;
            phone?: string;
        };
        ApiResponseReturnClass: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnClass"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnClass: {
            /** Format: date-time */
            timestamp?: string;
            data?: components["schemas"]["ReturnDataClass"];
            userLogin?: components["schemas"]["UserModel"];
            refreshToken?: string;
            error?: boolean;
            msg?: string;
            code?: string;
            success?: boolean;
            MSG?: string;
            Code?: string;
        };
        ReturnDataClass: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: Record<string, never>[];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        TransactionDTO: {
            /** Format: uuid */
            to_account_id?: string;
            /** Format: uuid */
            from_account_id?: string;
            /** @enum {string} */
            type?: "WITHDRAW" | "DEPOSIT" | "TRANSFER";
            amount?: number;
            note?: string;
            reference_no?: string;
            to_account_number?: string;
            from_account_number?: string;
            /** Format: date-time */
            created_at?: string;
        };
        UserAccountResponse: {
            /** Format: uuid */
            id?: string;
            accountNumber?: string;
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
        };
        ApiResponseReturnDataClass: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClass"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseMapStringObject: {
            success?: boolean;
            message?: string;
            data?: {
                [key: string]: Record<string, never>;
            };
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        LoginDTO: {
            email?: string;
            password?: string;
        };
        ApiResponseListTransactionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["TransactionDTO"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseListStockModel: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StockModel"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        StockModel: {
            symbol?: string;
            name?: string;
            industry?: string;
            logo?: string;
            type?: string;
            marketCap?: number;
        };
        Account: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
        };
        AccountResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RequestDTO: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            requestType?: "OPEN_ACCOUNT" | "CHANGE_ACCOUNT_STATUS" | "CHANGE_ACCOUNT_TYPE" | "OPEN_PORTFOLIO";
            requestType?: "OPEN_ACCOUNT" | "CHANGE_ACCOUNT_STATUS" | "CHANGE_ACCOUNT_TYPE";
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
            data?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            approvedAt?: string;
            account?: components["schemas"]["Account"];
            approveBy?: components["schemas"]["UserModel"];
            accountRequest?: components["schemas"]["AccountResponse"];
        };
        ApiResponseRequestDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["RequestDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        PortfolioDTO: {
            accountNumber?: string;
            reason?: string;
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "CLOSED" | "FROZEN";
            /** Format: date-time */
            createdAt?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            portfolioId?: string;
            user?: components["schemas"]["UserModel"];
            details?: components["schemas"]["PortfolioDetailModel"][];
        };
        PortfolioDetailModel: {
            /** Format: uuid */
            id?: string;
            amount?: number;
            avg_price?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            portfolio?: components["schemas"]["PortfolioModel"];
            stock?: components["schemas"]["StockModel"];
        };
        PortfolioModel: {
            /** Format: uuid */
            id?: string;
            accountNumber?: string;
            reason?: string;
            /** @enum {string} */
            status?: "PENDING" | "ACTIVE" | "CLOSED" | "FROZEN";
            /** Format: date-time */
            createdAt?: string;
            user?: components["schemas"]["UserModel"];
            portfolioDetails?: components["schemas"]["PortfolioDetailModel"][];
        };
        OrderDTO: {
            /** Format: uuid */
            id?: string;
            price?: number;
            amount?: number;
            /** @enum {string} */
            type?: "BUY" | "SELL";
            /** Format: date-time */
            createdAt?: string;
            /** @enum {string} */
            status?: "OPEN" | "MATCHED" | "PARTIAL" | "CANCELLED" | "PENDING";
            /** Format: uuid */
            portfolioId?: string;
            symbol?: string;
            /** Format: uuid */
            accountId?: string;
            portfolio?: components["schemas"]["PortfolioModel"];
            stock?: components["schemas"]["StockModel"];
        };
        CreateAccountRequest: {
            /** @enum {string} */
            accountType: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            initialDeposit?: number;
        };
        ApiResponseAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ChangeAccountTypeRequest: {
            accountType: string;
        };
        ChangeStatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
        };
        ApiResponseReturnDataClassUserDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassUserDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassUserDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["UserDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseReturnDataClassTransactionDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassTransactionDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassTransactionDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["TransactionDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseReturnDataClassStockDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassStockDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassStockDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["StockDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        StockDTO: {
            symbol?: string;
            name?: string;
            industry?: string;
            logo?: string;
            type?: string;
            marketCap?: number;
        };
        ApiResponseStockPriceDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["StockPriceDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        StockPriceDTO: {
            currentPrice?: number;
            change?: number;
            percentChange?: number;
            high?: number;
            low?: number;
            open?: number;
            previousClose?: number;
            /** Format: int64 */
            timestamp?: number;
        };
        ApiResponseReturnDataClassRequestDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassRequestDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassRequestDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["RequestDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseReturnDataClassPortfolioDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassPortfolioDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassPortfolioDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["PortfolioDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponsePortfolioDetailDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PortfolioDetailDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        PortfolioDetailDTO: {
            amount?: number;
            avg_price?: number;
            /** Format: uuid */
            portfolioId?: string;
            symbol?: string;
        };
        ApiResponseReturnDataClassOrderDTO: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ReturnDataClassOrderDTO"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ReturnDataClassOrderDTO: {
            transactionList?: components["schemas"]["TransactionDTO"][];
            userList?: components["schemas"]["UserDTO"][];
            accountList?: components["schemas"]["UserAccountResponse"][];
            content?: components["schemas"]["OrderDTO"][];
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            currentPage?: number;
            /** Format: int32 */
            pageSize?: number;
            first?: boolean;
            last?: boolean;
        };
        ApiResponseListAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AccountResponse"][];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        ApiResponseBalanceResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BalanceResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        BalanceResponse: {
            accountNumber?: string;
            balance?: number;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponsePageAccountResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageAccountResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageAccountResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AccountResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        AccountWithOwnerResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            accountNumber?: string;
            /** @enum {string} */
            accountType?: "SAVINGS" | "CURRENT_PERSONAL" | "CURRENT_CORPORATE" | "FIXED_DEPOSIT_PERSONAL" | "FIXED_DEPOSIT_CORPORATE";
            /** @enum {string} */
            accountCategory?: "SAVINGS" | "CURRENT" | "FIXED_DEPOSIT";
            balance?: number;
            /** @enum {string} */
            status?: "ACTIVE" | "CLOSED" | "FROZEN" | "PENDING" | "REJECTED_REQUEST";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            ownerName?: string;
        };
        ApiResponsePageAccountWithOwnerResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PageAccountWithOwnerResponse"];
            error?: components["schemas"]["ErrorDetail"];
            /** Format: date-time */
            timestamp?: string;
        };
        PageAccountWithOwnerResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AccountWithOwnerResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllUser: {
        parameters: {
            query: {
                size: number;
                page: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassUserDTO"];
                };
            };
        };
    };
    editUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserModel"];
                };
            };
        };
    };
    approveRequest: {
        parameters: {
            query: {
                isApprove: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnClass"];
                };
            };
        };
    };
    approvePortRequest: {
        parameters: {
            query: {
                isApprove: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnClass"];
                };
            };
        };
    };
    approveOrder: {
        parameters: {
            query: {
                isApprove: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnClass"];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClass"];
                };
            };
        };
    };
    RefreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMapStringObject"];
                };
            };
        };
    };
    getAllTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionDTO"];
                };
            };
        };
    };
    postTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListTransactionDTO"];
                };
            };
        };
    };
    getAllStock: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassStockDTO"];
                };
            };
        };
    };
    importStock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListStockModel"];
                };
            };
        };
    };
    getAllRequest: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassRequestDTO"];
                };
            };
        };
    };
    postRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestDTO"];
                };
            };
        };
    };
    getPortfolioRequest: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "INACTIVE" | "SUSPENDED" | "PENDING" | "APPROVED" | "CANCELLED" | "REJECTED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassRequestDTO"];
                };
            };
        };
    };
    postPortfolioRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRequestDTO"];
                };
            };
        };
    };
    getAllOrder: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassOrderDTO"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnClass"];
                    "*/*": components["schemas"]["ApiResponseListTransactionDTO"];
                };
            };
        };
    };
    getAllAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListAccountResponse"];
                };
            };
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeAccountType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeAccountTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeAccountStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    changeBalance: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    getTransactionByUserId: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassTransactionDTO"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query: {
                page: number;
                size: number;
            };
            header?: never;
            path: {
                accNum: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassTransactionDTO"];
                };
            };
        };
    };
    getStockPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStockPriceDTO"];
                };
            };
        };
    };
    getPortfolioByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassPortfolioDTO"];
                };
            };
        };
    };
    getAllRequest_1: {
        parameters: {
            query: {
                portfolioId: string;
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePortfolioDetailDTO"];
                };
            };
        };
    };
    getAllOrderByUserId: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReturnDataClassOrderDTO"];
                };
            };
        };
    };
    getAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBalanceResponse"];
                };
            };
        };
    };
    getAccountFromId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAccountResponse"];
                };
            };
        };
    };
    getAccountByUserId: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAccountResponse"];
                };
            };
        };
    };
    getAllAccountAdmin: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageAccountWithOwnerResponse"];
                };
            };
        };
    };
}
