spring:
  application:
    name: banking-system

  datasource:
#    url: jdbc:postgresql://localhost:5432/banking_db
#    username: postgres
#    password: postgres
    
#    LOCALHOST
    url: jdbc:postgresql://dpg-d6s2h7kr85hc73emgo6g-a.singapore-postgres.render.com:5432/banksystem_a6cy
    username: banksystem_a6cy_user
    password: DnpQblWLecfZ1RMl3oTI38ZJBCb4wn4P

#    Production
#     url: ${DATABASE_URL}
#     username: ${DATABASE_USERNAME}
#     password: ${DATABASE_PASSWORD}
#     driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: false   # ปิดไว้ก่อน เปิดทีหลังเมื่อพร้อม

  # # Flyway — จัดการ DB migration (แนะนำใช้แทน ddl-auto: create)
  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baseline-on-migrate: true

# Server
server:
  port: 8080
  servlet:
    context-path: /api          # ทุก endpoint จะขึ้นต้นด้วย /api

# JWT
jwt:
  secret: ${JWT_SECRET:dev-secret-key-for-local-only-min-32-chars}
  access-token-expiry: 900000   # 15 นาที
  refresh-token-expiry: 604800000 # 7 วัน

# App custom config
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

# Logging
logging:
  level:
    com.banking: DEBUG           # log แค่ package ของเรา
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs